apiVersion: apps/v1
kind: Deployment

metadata:
  name: portfolio-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: portfolio-backend

  template:
    metadata:
      labels:
        app: portfolio-backend
        {{- include "portfolio.labels" . | nindent 8 }}

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - secretRef:
                name: {{ .Values.backend.envFromSecret }}

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}