apiVersion: v1
kind: ServiceAccount

metadata:
  name: portfolio-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}

automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: portfolio-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}

automountServiceAccountToken: false